version: '3'

services:
    nginx:
        image: nginx
        volumes:
            - '/root/me:/var/www'
            - '/root/me/site/nginx/site.conf:/etc/nginx/conf.d/site.conf'
        deploy:
            labels:
                - "traefik.enable=true"
                - "traefik.http.routers.me.rule=Host(`me.418.ovh`)"
                - "traefik.http.routers.me.tls=true"
                - "traefik.http.routers.me.tls.certresolver=mytlschallenge"
                - "traefik.http.services.me.loadbalancer.server.port=80" # it seems you always need to give traefik a port so it 'notices' the service
        networks:
            - shared-proxy


networks:
    shared-proxy:
        external: true