version: '3'

services:
    me:
        container_name: me
        image: nginx
        environment:
            - VIRTUAL_HOST=me.418.ovh
            - VIRTUAL_PORT=8002
            - LETSENCRYPT_HOST=me.418.ovh
            - LETSENCRYPT_EMAIL=avingtier@gmail.com
        networks:
            - network-proxy
        ports:
            - '8002:80'
        volumes:
            - '.:/var/www'
            - './site/nginx/site.conf:/etc/nginx/conf.d/site.conf'
networks:
    network-proxy:
        external:
            name: network-proxy