version: '3'

services:
    nginx:
        image: nginx
        environment:
            - VIRTUAL_HOST=me.418.ovh
            - VIRTUAL_PORT=8002
            - LETSENCRYPT_HOST=me.418.ovh
            - LETSENCRYPT_EMAIL=avingtier@gmail.com
        ports:
            - '8002:80'
        volumes:
            - '/root/me:/var/www'
            - '/root/me/site/nginx/site.conf:/etc/nginx/conf.d/site.conf'
        networks:
            - shared-proxy

networks:
    shared-proxy:
        external: true
